### ISSUE TITLE
몇가지 문제가 있어서 문의 드립니다.

### ISSUE THREAD

**Issue by rulitel** [axfree/DaumMovie.bundle#12]
한국 드라마 2014년 방영한 "나쁜 녀석들"  검색하면
개그 콘서트 "나쁜 녀석들" ,"나쁜 녀석들 : 악의도시"  두가지만 나옵니다.

그리고 예능 프로그램은 에피소드 번호가 틀린 프로가 몇게 있어서
전부 날짜로 파일 관리 하는데 전부는 아니고 몇몇 프로 최근 회차 정보를 못불러 옵니다. 
다른 방법이 있나요?

**Comment by axfree** [comment]
시리즈가 검색이 안되던 문제는 수정했습니다.
10094115015ab423967670ad6ed86f9f8f375738

회차 정보 문제는 문제가 되는 파일명을 알려주시면 확인해 보겠습니다.
날짜를 기반으로 에피소드 넘버링을 해 놨을 때도 회차정보를 매칭할 수 있도록 코드를 추가해 두긴 했습니다만... 이게 도움이 될지는 모르겠네요.

**Comment by rulitel** [comment]
늦은시간 확인 해주시고 수정 해주셔서 감사 합니다.

회차정보는 이게 맞는지 모르겠지만
기존에는 "2018-09-11" 이렇게 관리를 했는데
<li class="" data-clip="20180911" data-episode="348722">

프로그램 별로 적용 날짜는 다르지만  "20180918" 이렇게 변경 하면 불러 오는거 같습니다.
<li class="on" data-clip="20180918" data-episode="349307">

class="on" 이게 적용되어 있는 회차는 인식을 안되는거 같은데
yyyy-mm-dd ,yyyymmdd 관계없이 매칭되게 하려면 어떻게 해야 할까요?

**Comment by rulitel** [comment]
> 시리즈가 검색이 안되던 문제는 수정했습니다.
> [1009411](https://github.com/axfree/DaumMovie.bundle/commit/10094115015ab423967670ad6ed86f9f8f375738)
> 
> 회차 정보 문제는 문제가 되는 파일명을 알려주시면 확인해 보겠습니다.
> 날짜를 기반으로 에피소드 넘버링을 해 놨을 때도 회차정보를 매칭할 수 있도록 코드를 추가해 두긴 했습니다만... 이게 도움이 될지는 모르겠네요.

늦은시간 확인 해주시고 수정 해주셔서 감사 합니다.

회차정보는 이게 맞는지 모르겠지만
기존에는 "2018-09-11" 이렇게 관리를 했는데
<li class="" data-clip="20180911" data-episode="348722">

프로그램 별로 적용 날짜는 다르지만  "20180918" 이렇게 변경 하면 불러 오는거 같습니다.
<li class="on" data-clip="20180918" data-episode="349307">

class="on" 이게 적용되어 있는 회차는 인식을 안되는거 같은데
yyyy-mm-dd ,yyyymmdd 관계없이 매칭되게 하려면 어떻게 해야 할까요?

**Comment by axfree** [comment]
> 슈퍼맨이돌아왔다.E251_2018-09-16.720p-NEXT
> 슈퍼맨이돌아왔다.2018-09-16.720p-NEXT

두가지 모두 슈퍼맨이 돌아왔다 715회로 매칭되게 변경했습니다.
컬렉션은 제가 사용해 보지 않아서 잘 모르겠습니다 :)

**Comment by rulitel** [comment]
> > 슈퍼맨이돌아왔다.E251_2018-09-16.720p-NEXT
> > 슈퍼맨이돌아왔다.2018-09-16.720p-NEXT
> 
> 두가지 모두 슈퍼맨이 돌아왔다 715회로 매칭되게 변경했습니다.
> 컬렉션은 제가 사용해 보지 않아서 잘 모르겠습니다 :)

방금 확인 했습니다.
매우 잘됩니다.
바쁘 실텐데 신경써 주셔서 감사합니다.
잘사용 하겠습니다.

**Comment by ssampaq** [comment]
개그콘서트에서 에피소드 이름이 2번이 표현되는데 둘중 하나는 날짜를 표시부탁드립니다
언제나 감사하게 생각하며 사용중입니다. 

![1](https://user-images.githubusercontent.com/40530565/46256132-93bb2000-c4e1-11e8-8a27-fac35cd63676.PNG)
드

**Comment by axfree** [comment]
> 개그콘서트에서 에피소드 이름이 2번이 표현되는데 둘중 하나는 날짜를 표시부탁드립니다

개그콘서트는 확인해 보니 다음에서는 회차 정보를 제공하고 있지 않네요.
[개그콘서트 - Daum 검색](https://search.daum.net/search?w=tv&q=%EA%B0%9C%EA%B7%B8%EC%BD%98%EC%84%9C%ED%8A%B8&irk=48870&irt=tv-program&DA=TVP)

MBC, SBS는 실험적으로 다시보기 사이트에서 에피소드 정보를 끌어오게 해 봤습니다만... KBS도 고려는 해 보겠습니다.

**Comment by axfree** [comment]
TV: KBS 다시보기 사이트 지원 추가했습니다.
4209306c34beac0662f4fc26c05c1ab4f5a8d93d
