### ISSUE TITLE
Daum 메타데이터 회차가 아닌 날짜 기준 불러오기

### ISSUE THREAD

**Issue by Km81** [axfree/DaumMovie.bundle#13]
axfree 님, 먼저 좋은 번들 감사 드립니다.
해당 메타 데이터를 사용하면서, 아래와 같은 요구 사항이 있어 문의 드립니다.
현재 다음 TV 시리즈 메타 데이터는 에피소드 기준으로 불러오는 것으로 알고 있습니다.
그런데 최근 NEXT릴의 파일이 에피소드 번호가 다음 TV 시리즈 메타 데이터와 일치하지 않는 경우가 많습니다.
이에 에피소드 번호가 아닌 파일명에 있는 방영날짜 기준으로 메타 데이터를 업데이트할 수 있는 옵션이 추가될 수 있는 지 문의 드립니다.
가능하다면 반영 부탁 드리겠습니다.

**Comment by axfree** [comment]
파일명에 회차와 방송날짜가 모두 있는 경우 방송날짜 기준으로 에피소드가 잡히는 걸로 압니다.

> 슈퍼맨이 돌아왔다.E245.180930.720p-NEXT

이 경우는 다음에서 245회를 찾으므로 엉뚱한 정보가 나오지만, 방송날짜를 Plex Scanner가 인식할 수 있게 바꿔보면

> 슈퍼맨이 돌아왔다.E245.2018-09-30.720p-NEXT
> 슈퍼맨이 돌아왔다.2018-09-30.720p-NEXT

원하던 대로 2018-09-30에 방송된 717회로 매치가 됩니다.

에이전트 레벨에서는 자동으로 처리할 방법이 딱히 생각나질 않아서... 제가 권해 드리는 방법은...
파일명의 회차가 다음과 다르거나, 파일명에 회차가 없을 경우 파일명의 날짜부분만 YYYY-MM-DD 형식으로 바꿔준다.

> 슈퍼맨이 돌아왔다.E245.2018-09-30.720p-NEXT
> 출발 비디오 여행.2018-09-23.720p-NEXT

[Plex Series Scanner For Korea](https://github.com/soju6jan/Plex-Series-Scanner-For-Korea)라고 NEXT릴의 방송날짜를 인식하는 스캐너도 있던데 좀더 간단해 지려나요?

**Comment by Km81** [comment]
빠른 답변 감사합니다.
YYYY-MM-DD 형식일때 날짜 우선 매칭은 처음 알았습니다.
테스트 해보니, 현 디렉토리 상태에서 rename을 하니 메타데이터를 제대로 불러오지 못하고,
rename 된 파일을 다른 곳으로 옮겼다가 원래 위치로 이동 시키니 메타데이터를 날짜 기준으로 가지고 왔었습니다.
좋은 정보 감사합니다.

첨언하여, 말씀하신, Plex Series Scanner For Korea는 현재 사용 중이나, 다소 미스 매칭되는 부분이 있어, 
혹시나해서 건의 드린 사항이었습니다.

암튼 좋은 프로그램 감사 드리며, 잘 사용하도록 하겠습니다. ^^
