### ISSUE TITLE
.5관련 에피소드

### ISSUE THREAD

**Issue by bgs2313** [axfree/DaumMovie.bundle#14]
소드 아트 온라인 얼터너티브 건 게일 온라인을 매칭중 5.5항목이있습니다.
1화-5화까진 잘 불러와지는데 중간에 5.5항목은 건너뛰고 6화-이후로 적용됩니다.
정리시 제목.S01.E01[01화]....제목.S01.E06[5.5화]....제목.S01.E13[12화-최종화]
파일에피소드순서를 있는그대로 다음에서 불러와서 적용하면 될듯합니다.
적용검토여부 확인부탁드립니다.

**Comment by axfree** [comment]
.5는 일종의 스페셜 에피소드인것 같은데...
시즌을 00으로 해서 파일명을 바꾸면 스페셜로 분리되면서 메타데이타가 엉키는 문제가 사라질 것 같습니다.

```
제목.S01E01
제목.S01E02
...
제목.S01E05
제목.S00E05      ; S00은 Specials 시즌으로 따로 분리됨
제목.S01E06
...
제목.S01E12
```
tvdb에는 5.5화가 Specials E01로 등록돼 있으니 이렇게 하는게 낫겠네요.
```
제목.S00E01
or
Specials/제목.S00E01
```

다음이 스페셜이나 시즌을 지원하고 있지 않고, 일부 있는것도 처리가 일관되지 않기 때문에 에이전트 차원에서 일일이 대응하기 어려워 현재는 지원하고 있지 않습니다.
