### ISSUE TITLE
안녕하세요 axfree님 신규자료 추가시 일치항목 검색이 안되는것 같습니다.

### ISSUE THREAD

**Issue by airbogo** [axfree/DaumMovie.bundle#16]
axfree님 메타는 axfree님 번들은 항상 모니터링하고 있어서 신규등록되면 바로업데이트 하거든요.. 이번에 업데이트 후 신규자료 일부 검색이 안되는 것 같아 문의 드립니다. 다른 번들(daum movie tv series)에서 테스트 해봤는데 이 버전은 검색됩니다.
시간되실때 수정좀 부탁드릴게요 
감사드립니다. ^^

**Comment by axfree** [comment]
어떤게 안되는지 힌트를 주시면 확인해 보겠습니다.

**Comment by airbogo** [comment]
네 일단 중국드라마 "전하를 조심해" 검색해도 안나오구요..다른것도 몇번 그랬는데 좀 확인해봐야 될 것 같아요
