### ISSUE TITLE
제목 초성 색인 관련 질문

### ISSUE THREAD

**Issue by truthfulie** [axfree/DaumMovie.bundle#33]
제목 초성으로 색인 하는 옵션이 있어서 깔끔하게 정리되서 너무 좋네요. 

근데 한가지 문제점? 이 있는데 이부분에 대해서 좀 물어볼게요. 가끔 수동으로 제목을 바꾸고 싶은 타이틀들이 있어요. 

예로 '미스터리 음악쇼 복면가왕' 이란 타이틀을 짤막하게 '복면가왕' 으로 수정하면 초성 색인이 이에 맞게 업데이트 되지 않아요.

만들어주신 에이전트 사용하기 전에는 노가다로 sort title 앞에 초성을 달아줬는데...이 방법을 사용하면 

에이전트가 생성한 초성 색인 'ㅂ' 에 제가 수동으로 생성한 'ㅂ'이 합쳐지질 않고 새로운 ㅂ항목을 만드네요.

이게 두개 있는건 그리 큰 문제는 아닌데 제가 만든 'ㅂ' 은 에이전트가 자동으로 만든 'ㅎ' 다음으로 정렬되네요.

수동으로 타이틀 바꾸고 싶은 경우 이런 현상 일어나는걸 피할수 있는 방법이 없을까요?

**Comment by axfree** [comment]
제목을 초성 정렬이 되게 하기 위해서 음절을 분해해 놔서 그렇습니다.

[Hangul Jamo (Unicode block)](https://en.wikipedia.org/wiki/Hangul_Jamo_(Unicode_block))
위 링크의 한글자모표에서 제목의 첫글자에 해당하는 한글 자모를 복사해서 넣어보세요.

"복" > "ᄇ" + "ᅩ" + "ᆨ"

**Comment by truthfulie** [comment]
빠른 답변 감사합니다! 말씀하신데로 복붙하니 깔끔하게 정렬되네요! 감사합니다.
