### ISSUE TITLE
로컬 자막 파일 인식 문제?

### ISSUE THREAD

**Issue by truthfulie** [axfree/DaumMovie.bundle#34]
에이젼트 사용시 영상폴더에 넣어둔 로컬 자막 파일 인식이 안되고 있습니다. 

Sub-Zero 에이젼트 사용해서 로컬 자막 파일을 받습니다.

근데 이상하게도 DaumMovie 를 사용하면 자막 선택 드롭 메뉴에서 external 자막을 보여주지 않네요.

제가 라이브러리를 두개 만들어서 하나는 plex movie 사용해서 영어로 쓰고

다른 하나는 axfree님의 daummoivie 사용합니다.

물론 영화 폴더는 둘다 같은 폴더를 지정해줬고 에이젼트 설정 화면에서 Local Media Assets는 활성화 확인하였습니다.

왜인지 모르겠는데 plex movie 로 설정한 라이브러리에선 외부 자막 인식이 잘되는데 

똑같은 폴더를 지정해준 daummovie 로 설정한 라이브러리에선 자막 파일을 읽어오지 않습니다.

제가 뭔가 설정을 잘못한걸까요?

**Comment by axfree** [comment]
서버 > SETTINGS > Agents > Movies > Daum Movie > Local Media Assets (Movies)

위 체크박스를 체크하면 제 경우에는 자막이 나타나네요. 웹에서 설정할 때 저장 버튼이 없어서 그런지 설정이 변경이 안되는 경우가 있는 듯 합니다. 여러번 확인 하신 후, 해당 영화로 가서 Refresh Metadata 해 보세요.

**Comment by rexx6** [comment]
저도 언젠가부터 외부 smi파일 자막이 안나와서

이것저것 다 해보다가, 흘러흘러 여기까지 왔는데...

위에 axfree님 언급하신대로 설정대로 해보니, 제대로 나오네요.

저게 문제였네요. 덕분에 해결했습니다.

감사합니다.
