### ISSUE TITLE
TV제목 검색이 특정 프로그램에만 안됩니다.

### ISSUE THREAD

**Issue by rexx6** [axfree/DaumMovie.bundle#35]
안녕하세요.

개발해주신 프로그램 감사히 잘 사용하고 있습니다.

TV에 대해 특정 프로그램만 제목을 통해 검색이 안됩니다.

의외로 수동으로 "일치항목 수정"을 통해 검색하면 잘 찾아줍니다. 그래서 매번 일일이 수동으로 수정해 주고 있습니다.

해당 프로그램은 아래와 같습니다.

확인 부탁드립니다.

> 이십세기 힛-트쏭.E47.210212.720p-NEXT
> 이십세기 힛-트쏭.E48.210219.720p-NEXT
> 극한직업.E955.210210.720p-NEXT
> 극한직업.E956.210217.720p-NEXT

감사합니다.

**Comment by axfree** [comment]
타이틀의 미묘한 차이로 인해 자동 매칭이 안되는 문제를 해결하기 위해 매칭 점수를 조금씩 상향했습니다.
감사합니다.

0c65d85444f96ca67427b3836618f98946912a13

**Comment by rexx6** [comment]
잘됩니다. 감사합니다.
