### ISSUE TITLE
절대로 안불러와지는 메타데이터가 있습니다.

### ISSUE THREAD

**Issue by gw1021** [axfree/DaumMovie.bundle#5]
중2병이라도 사랑을 하고 싶어!
라는 TV 애니메이션인데요 다음영화에는 등록되어있는데 절대로 안불러와지는거 같습니다.
확인가능하시면 확인한번 해주시면 감사드리겠습니다.

++ 추가적인 문제
업 (2009)
원제 Up
이라는 디즈니 영화를 검색했을 때 원제 검색이 우선적인 것인지 Up in the Air(인 디 에어 (2009))라는 영화로 메타데이터가 불러와집니다.

**Comment by axfree** [comment]
이번 변경 사항 적용 때문인지는 확실치 않지만, 지금은 되는 거 같습니다.
검색 결과 순위 문제는... 시간 날 때 개선할 점이 있는지 살펴보겠습니다.

감사합니다.
