### ISSUE TITLE
다음영화가 바뀌어서 안되는거 같습니다.

### ISSUE THREAD

**Issue by zestti** [axfree/DaumMovie.bundle#52]
다음 영화가 바뀐거 같습니다. 그래서 에이전트가 작동이 안되는거 같습니다.

**Comment by andrewsohn80** [comment]
그런 것 같습니다. 얼마 전에 다음에서 중단한다고 안내하더니 이젠 작동을 안 하네요..

**Comment by totoli78** [comment]
정말 오랜 세월동안 Plex와 함께 사용해왔던 플러그인 이었는데..  아쉽고 안타까운 일이네요.
